import { createStore, combineReducers, applyMiddleware, compose } from 'redux'
import { composeWithDevTools } from 'redux-devtools-extension/logOnlyInProduction.js'

import asynchronousMiddleware from './middleware/asynchronous.js'
import routerMiddleware from './middleware/router.js'

import reactPagesReducer from './reducer.js'

import { checkForAutogeneratedEventNameCollision } from './naming.js'

import processRoutes from './processRoutes.js'

import {
	foundReducer,
	createRouterStoreEnhancers,
	initializeRouter
} from '../router/index.js'

export default function _createStore({
	initialState: data,
	createHistoryProtocol,
	httpClient,
	stash,
	settings,
	options
}) {
	const {
		routes,
		reducers,
		reduxMiddleware,
		reduxStoreEnhancers,
		reduxEventNaming,
		http,
		onLoadError,
		getLocale,
		codeSplit,
		load
	} = settings

	const {
		server,
		devtools,
		stats,
		onBeforeNavigate,
		onNavigate,
		getCookie
	} = options

	processRoutes(routes, {
		stash,
		codeSplit,
		server,
		onLoadError,
		getLocale,
		getCookie
	})

	// Redux middleware.
	// User may supply their own Redux middleware.
	const middleware = reduxMiddleware ? reduxMiddleware() : []

	// Built-in middleware.
	middleware.push(
		// Asynchronous middleware (e.g. for HTTP Ajax calls).
		asynchronousMiddleware({
			httpClient,
			reduxEventNaming,
			server,
			onError: http.onError,
			getErrorData: http.getErrorData
		})
	)

	if (!server) {
		middleware.push(routerMiddleware({
			routes,
			codeSplit,
			onBeforeNavigate,
			onNavigate,
			reportStats: stats,
			stash
		}))
	}

	// Redux "store enhancers"
	const storeEnhancers = []

	// User may supply his own Redux store enhancers.
	if (reduxStoreEnhancers) {
		storeEnhancers.push(...reduxStoreEnhancers())
	}

	storeEnhancers.push(...createRouterStoreEnhancers(routes, createHistoryProtocol, {
		basename: settings.basename
	}))

	// Redux middleware are applied in reverse order.
	// (which is counter-intuitive)
	storeEnhancers.push(applyMiddleware(...middleware))

	// Create Redux store.
	const store = getStoreEnhancersComposer(server, devtools)(...storeEnhancers)(createStore)(createReducer(reducers), data)

	// On the client side, add `hotReload()` function to the `store`.
	// (could just add this function to `window` but adding it to the `store` fits more)
	if (!server) {
		// `hotReload` helper function gives the web application means to hot reload its Redux reducers
		store.hotReload = (reducers) => store.replaceReducer(createReducer(reducers))
	}

	// Initialize `found`.
	initializeRouter(store)

	// Return the Redux store
	return store
}

function createReducer(reducers) {
	// Check for reserved reducer names.
	for (const reducerName of RESERVED_REDUCER_NAMES) {
		if (reducers[reducerName]) {
			throw new Error(`"${reducerName}" reducer name is reserved.`)
		}
	}
	// Check for `ReduxModule` autogenerated event names conflicts.
	checkForAutogeneratedEventNameCollision(reducers)
	// Clone the object because it will be modified.
	reducers = { ...reducers }
	// Add router reducer.
	reducers[ROUTER_REDUCER_NAME] = foundReducer
	// Add `react-pages` reducer.
	reducers[REDUCER_NAME] = reactPagesReducer
	// Create the combined reducer.
	return combineReducers(reducers)
}

function getStoreEnhancersComposer(server, devtools) {
	// Redux DevTools aren't used on the server side
	if (server) {
		return compose
	}

	// Custom behaviour
	if (devtools && devtools.compose) {
		return devtools.compose
	}

	// With custom options
	if (devtools && devtools.options) {
		return composeWithDevTools(devtools.options)
	}

	// Without custom options
	return composeWithDevTools
}

// This library stores its data in "pages" property of Redux state.
export const REDUCER_NAME = 'pages'

// `found` router library stores its state in "found" property of Redux state.
export const ROUTER_REDUCER_NAME = 'found'

// `farce` history management library stores its state in "location" property of Redux state.
const HISTORY_REDUCER_NAME = 'location'

const RESERVED_REDUCER_NAMES = [
	REDUCER_NAME,
	ROUTER_REDUCER_NAME,
	HISTORY_REDUCER_NAME
]